### ISSUE TITLE
Fix the README file for helix editor

### ISSUE THREAD

**Issue by jlb6907** [c3lang/tree-sitter-c3#20]
In the README file, in the Helix section, you should have : 

```toml
[language-server.c3-lsp]
command = "c3lsp"
```

Instead of 

```toml
[language-server.c3-lsp]
command = "c3-lsp"
```

Binary name changed to c3lsp in [v0.3.1](https://github.com/pherrymason/c3-lsp/releases/tag/v0.3.1).
